export const dummyPatients = [
  {
    patientName: "Rahul Sharma",
    dob: "1988-05-14",
    patientId: "PAT001",
    policyNumber: "SUK12345",
    insuranceCompany: "Sukoon",
    treatmentCategory: ["Cardiology", "Oncology"],
    treatmentDate: "2025-01-10",
    hospital: "Apollo Hospital Mumbai",
    physician: "Dr. Amit Verma",
  },
  {
    patientName: "Priya Mehta",
    dob: "1992-09-22",
    patientId: "PAT002",
    policyNumber: "SUK67890",
    insuranceCompany: "Tokkio",
    treatmentCategory: ["Dental"],
    treatmentDate: "2025-02-15",
    hospital: "Fortis Hospital Mulund",
    physician: "Dr. Sneha Kulkarni",
  },
  {
    patientName: "Amit Patel",
    dob: "1979-03-18",
    patientId: "PAT003",
    policyNumber: "SUK12345",
    insuranceCompany: "Sukoon",
    treatmentCategory: ["Orthopedic", "Surgery", "Gastroenterology"],
    treatmentDate: "2025-01-28",
    hospital: "Nanavati Max Hospital",
    physician: "Dr. Rajesh Nair",
  },
  {
    patientName: "Neha Reddy",
    dob: "1995-11-05",
    patientId: "PAT004",
    policyNumber: "SUK67890",
    insuranceCompany: "Tokkio",
    treatmentCategory: ["Neurology"],
    treatmentDate: "2025-03-02",
    hospital: "Kokilaben Ambani Hospital",
    physician: "Dr. Kavita Rao",
  },
  {
    patientName: "Vikram Singh",
    dob: "1983-07-30",
    patientId: "PAT005",
    policyNumber: "SUK12345",
    insuranceCompany: "Sukoon",
    treatmentCategory: ["Surgery", "Oncology"],
    treatmentDate: "2025-02-05",
    hospital: "Lilavati Hospital Bandra",
    physician: "Dr. Anil Kapoor",
  },
  {
    patientName: "Anjali Desai",
    dob: "1990-01-12",
    patientId: "PAT006",
    policyNumber: "SUK67890",
    insuranceCompany: "Tokkio",
    treatmentCategory: ["Cardiology", "Dermatology"],
    treatmentDate: "2025-01-20",
    hospital: "Apollo Hospital Mumbai",
    physician: "Dr. Meera Shah",
  },
  {
    patientName: "Karan Malhotra",
    dob: "1986-04-25",
    patientId: "PAT007",
    policyNumber: "SUK12345",
    insuranceCompany: "Sukoon",
    treatmentCategory: ["Dental", "Gastroenterology"],
    treatmentDate: "2025-03-10",
    hospital: "Fortis Hospital Mulund",
    physician: "Dr. Rohit Joshi",
  },
  {
    patientName: "Sneha Iyer",
    dob: "1998-06-17",
    patientId: "PAT008",
    policyNumber: "SUK67890",
    insuranceCompany: "Tokkio",
    treatmentCategory: ["Orthopedic"],
    treatmentDate: "2025-02-22",
    hospital: "Nanavati Max Hospital",
    physician: "Dr. Sunil Gupta",
  },
  {
    patientName: "Arjun Kapoor",
    dob: "1981-12-09",
    patientId: "PAT009",
    policyNumber: "SUK12345",
    insuranceCompany: "Sukoon",
    treatmentCategory: ["Neurology", "Oncology"],
    treatmentDate: "2025-03-12",
    hospital: "Kokilaben Ambani Hospital",
    physician: "Dr. Ritu Menon",
  },
  {
    patientName: "Pooja Nair",
    dob: "1993-08-19",
    patientId: "PAT010",
    policyNumber: "SUK67890",
    insuranceCompany: "Tokkio",
    treatmentCategory: ["Pediatrics"],
    treatmentDate: "2025-02-18",
    hospital: "Lilavati Hospital Bandra",
    physician: "Dr. Vivek Chandra",
  },
];
